### ISSUE TITLE
Cant run on a raspberry pi

### ISSUE THREAD

**Issue by LukasOchmann** [Hentra/dyndns-netcup-go#14]
Hi @Hentra, 
i try to run this on an raspberry pi 4 b with rasbian installed. 
I had to specify the platform in my compose file, otherwise it would not start.
```yml
  netcup:
    container_name: netcup
    restart: unless-stopped
    image: ghcr.io/hentra/dyndns-netcup-go
    platform: linux/x86_64
    volumes:
      - './netcup/confi.yml:/config.yml'
    environment:
      - INTERVAL=300
``` 
now, the following error is present in the logs:
```
exec /dyndns-docker: exec format error
```

do you have an idea how i can fix that?
